### ISSUE TITLE
parsing error when trying to process multiple vcard entries that was exported from icloud

### ISSUE THREAD

**Issue by hqtsky** [jhermsmeier/node-vcf#35]
I exported a set of contacts from my icloud.com account. This file appears to be correct but when importing using the multiple imports method I get this error:

`SyntaxError: Invalid vCard: Expected "VERSION:\d.\d" but found "undefined"`

Here is how read and import the file:
```
var contactData = fs.readFileSync("./samples/multiple-contacts-from-icloud.vcf","utf8", "utf8");
var contacts = vCard.parse(contactData); //multiple
```

I've attached my sample file here, i appended the '.txt' extension to allow attach here. 
[multiple-contacts-from-icloud.vcf.txt](https://github.com/jhermsmeier/node-vcf/files/3715135/multiple-contacts-from-icloud.vcf.txt)

**Comment by hqtsky** [comment]
I suspected that Apple/iCloud file export only used newline ascii 10 or x0A. So i replaced it with the carriage return, newline.. I wonder if this could be added to the normalize() sequence.
`contactData = contactData.replace(new RegExp(String.fromCharCode(10), 'g'), '\r\n');`

**Comment by jhermsmeier** [comment]
Thanks, but due to https://github.com/jhermsmeier/node-vcf/pull/31 we cannot add this to the normalization, as also further touched on in https://github.com/jhermsmeier/node-vcf/issues/34#issuecomment-539410643. TLDR; it breaks other things. So unfortunately users of this module will have to replace LF -> CRLF themselves, *if they know it is safe to do so*.

> I suspected that Apple/iCloud file export only used newline ascii 10 or x0A.

I'd think that it would emit a VCF file with CRLF, but have never tested it. Could also be that a text editor automatically translated CRLF -> LF, if you opened the file in one by any chance? (That seems to be a common occurrence)
