### ISSUE TITLE
unable to parse

### ISSUE THREAD

**Issue by statusunknown418** [jhermsmeier/node-vcf#52]
I'm trying to parse simple vcards but there's always an error saying `unsupported version <message>`

```tsx
// raw input
const vCard = new VCF().parse(`
BEGIN:VCARD\r\n
VERSION:3.0\r\n
REV:2024-07-30T00:54:34.412Z\r\n
N;CHARSET=utf-8:John Doe;;;;\r\n
FN;CHARSET=utf-8:John Doe\r\n
NICKNAME:Johnny\r\n
ORG;CHARSET=utf-8:Example Corp.;CEO & founder\r\n
PHOTO;VALUE=uri:https://picsum.photos/200\r\n
URL:https://example.com\r\n
TITLE;CHARSET=utf-8:CEO\r\n
X-SOCIALPROFILE;type=Twitter;x-user=statusunknown418:https://x.com/\r\n
EMAIL;INTERNET:john.doe@example.com\r\n
TEL:+1 (555) 555-5555
ADR;WORK;POSTAL;CHARSET=utf-8:Home Address;Extended Address here;Menlo Park;San Francisco;CA;94025;US\r\n
NOTE;CHARSET=utf-8:This is a note\r\n
END:VCARD\r\n
`);
```

plus it will crash if I don't include the `\r\n`

**Comment by jhermsmeier** [comment]
In this case that's because the `\n` is one too many, new lines in template literals implicitly add a `\n`, resulting in `BEGIN:VCARD\r\n\n` – to get just the CRLF `\r\n`, leave the `\n`, or put everything on one line; for example

```js
const vCard = new VCF().parse(`BEGIN:VCARD\r\nVERSION:3.0\r\nREV:2024-07-30...
```

or

```js
const vCard = new VCF().parse(`
BEGIN:VCARD\r
VERSION:3.0\r
...
```

> plus it will crash if I don't include the \r\n

Please see https://github.com/jhermsmeier/node-vcf/issues/51#issuecomment-2145232537
